---
version: '3'
tasks:
    cargo-install-skyline: 
        cmd: cargo install cargo-skyline
        desc: "Installs the cargo-skyline crate."
        status:
            - cargo skyline --help
        preconditions: 
            - cargo --help
    copy-lua-and-cpp-files:
        cmds: 
            - find {{.SKYLINE_DIR}} -type f -name "cpp.rs" | xargs cp -t .
            - find {{.SKYLINE_DIR}} -type f -name "lua_const.rs" | xargs cp -t .
        desc: "Find the `cpp.rs` and `lua_const.rs` files and copy them to the project root."
        status: 
            - test -f cpp.rs 
            - test -f lua_const.rs
        vars: 
            SKYLINE_DIR: "$HOME/.cargo/git/checkouts/skyline-smash-714c6bb550307c21"
    default: 
        cmds: 
            - task: init-submodules
            - task: cargo-skyline-install
            - task: get-param-hashes
            - task: copy-lua-and-cpp-files
        desc: "Performs all necessary steps to help you get started to mod SSBU."
    get-param-hashes:
        cmd: curl -O https://raw.githubusercontent.com/ultimate-research/param-labels/master/ParamLabels.csv
        desc: "Download Ultimate-Research's spreadsheet containing hashes for (almost) every value in the game."
        preconditions: 
            - curl --help
        status: 
            - test -f ParamLabels.csv
    init-submodules:
        cmd: git submodule update --init 
        desc: "Adds WuBoytH's smashline plugin development template and dumped SSBU scripts to the project root." 
        preconditions: 
            - git --help
