---
version: '3'
tasks:
    _partial-clone-ssbu-scripts:
        cmd: git clone -n --depth=1 --filter=tree:0 https://github.com/WuBoytH/SSBU-Dumped-Scripts.git
        internal: true
        status: 
            - test -d SSBU-Dumped-Scripts
    _partial-clone-ssbu-motion-lists:
        cmd: git clone -n --depth=1 --filter=tree:0 https://github.com/WuBoytH/SSBU-Dumped-Motion-Lists.git        
        internal: true
        status: 
            - test -d SSBU-Dumped-Motion-Lists
    cargo-install-skyline: 
        cmd: cargo install cargo-skyline
        desc: "Installs the cargo-skyline crate."
        status:
            - cargo skyline --help
        preconditions: 
            - cargo --help
    copy-lua-and-cpp-files:
        cmds: 
            - find {{.SKYLINE_DIR}} -type f -name "cpp.rs" | xargs cp -t .
            - find {{.SKYLINE_DIR}} -type f -name "lua_const.rs" | xargs cp -t .
        desc: "Find the `cpp.rs` and `lua_const.rs` files and copy them to the project root."
        status: 
            - test -f cpp.rs 
            - test -f lua_const.rs
        vars: 
            SKYLINE_DIR: "$HOME/.cargo/git/checkouts/skyline-smash-714c6bb550307c21"
    default: 
        cmds: 
            - task: init-wuboy-submodule
            - task: cargo-install-skyline
            - task: get-param-hashes
            - task: get-smashline-script-dump
            - task: get-global-table
            - task: get-fighter-motion-list-dump
        desc: "Performs all necessary steps to help you get started to mod SSBU."
    get-global-table:
        cmd: curl -O https://raw.githubusercontent.com/WuBoytH/The-WuBor-Patch/dev/WuBor-Utils/src/table_const.rs
        desc: "Adds WuBoytH's file containing global constants regarding fighter states."
        preconditions: 
            - curl --help 
        status: 
            - test -f table_const.rs
    get-fighter-motion-list-dump:
        cmds: 
            - git sparse-checkout set --no-cone fighter
            - git checkout 
        dir: SSBU-Dumped-Motion-Lists
        desc: "Adds WuBoytH's smashline template scripts for all characters' attacks. Not a submodule to avoid unnecessary downloads."
        deps: 
            - _partial-clone-ssbu-motion-lists
        status: 
            - test -d smashline
    get-param-hashes:
        cmd: curl -O https://raw.githubusercontent.com/ultimate-research/param-labels/master/ParamLabels.csv
        desc: "Download The Smash Ultimate Research Group's spreadsheet containing hashes for (almost) every value in the game."
        preconditions: 
            - curl --help
        status: 
            - test -f ParamLabels.csv
    get-smashline-script-dump:
        cmds: 
            - git sparse-checkout set --no-cone smashline
            - git checkout 
        dir: SSBU-Dumped-Scripts
        desc: "Adds WuBoytH's smashline template scripts for all characters' attacks. Not a submodule to avoid unnecessary downloads."
        deps: 
            - _partial-clone-ssbu-scripts
        status: 
            - test -d smashline
    init-wuboy-submodule:
        cmd: git submodule update --init
        desc: "Adds WuBoytH's smashline plugin development template to the project root." 
        preconditions: 
            - git --help

