---
version: '3'
vars:
    BUILD_DIR: target/aarch64-skyline-switch/debug
    LOCAL_DEPLOY_DIR: "$HOME/d/Mods/smash/all_mods/plugins/"
tasks:
    build:
        cmd: cargo skyline build
        desc: "Build the NRO package."
    deploy-local:
        cmd: find target/aarch64-skyline-switch/debug -name "*.nro" -mtime -0.0001 | xargs mv -t {{.LOCAL_DEPLOY_DIR}}
        desc: "Deploy to a local path specified in dev/.env"
        deps:
            - build
